"""create transaction tables

Revision ID: a17fc3921d6d
Revises:
Create Date: 2026-01-23 15:33:27.603070

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a17fc3921d6d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_transaction_created"), "transaction", ["created"], unique=False)
    op.create_index(op.f("ix_transaction_updated"), "transaction", ["updated"], unique=False)
    op.create_index(op.f("ix_transaction_user_uuid"), "transaction", ["user_uuid"], unique=False)
    op.create_table(
        "outbox_event",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("aggregate_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_outbox_event_aggregate_id"), "outbox_event", ["aggregate_id"], unique=False)
    op.create_index(op.f("ix_outbox_event_processed"), "outbox_event", ["processed"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_event_processed"), table_name="outbox_event")
    op.drop_index(op.f("ix_outbox_event_aggregate_id"), table_name="outbox_event")
    op.drop_table("outbox_event")
    op.drop_index(op.f("ix_transaction_user_uuid"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_updated"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_created"), table_name="transaction")
    op.drop_table("transaction")
    # ### end Alembic commands ###
