
services:
  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - default
    restart: unless-stopped

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    restart: unless-stopped

  users-db:
    image: postgres:18.1-alpine
    container_name: users_database
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user_db" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - default
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: users
    container_name: userservice_app
    environment:
      - USER_SERVICE_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ./app/users:/app/app/users
      - ./app/core:/app/app/core
      - ./app/outbox_tests:/app/app/outbox_tests
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      users-db:
        condition: service_healthy
    networks:
      - default
    restart: unless-stopped
    command: >
      sh -c "sleep 15 && 
             uvicorn app.users.main:app --host 0.0.0.0 --port 8000"

  transaction-db:
    image: postgres:18.1-alpine
    container_name: transaction_database
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - transaction_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d transaction_db" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - default
    restart: unless-stopped

  transaction-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: transactions
    container_name: transactionservice_app
    environment:
      - TRANSACTION_SERVICE_ENV=development
    ports:
      - "8001:8001"
    volumes:
      - ./app/transactions:/app/app/transactions
      - ./app/core:/app/app/core
      - ./app/outbox_tests:/app/app/outbox_tests
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      transaction-db:
        condition: service_healthy
    networks:
      - default
    restart: unless-stopped
    command: >
      sh -c "sleep 15 && 
             uvicorn app.transactions.main:app --host 0.0.0.0 --port 8001"

  taskiq-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskiq_worker
    environment:
      - PAYMENT_SERVICE_ENV=development
      - WORKERS=2
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      transaction-db:
        condition: service_healthy
      users-db:
        condition: service_healthy
    networks:
      - default
    restart: unless-stopped
    command: >
      sh -c "sleep 15 && 
             cd /app &&
             python -m taskiq worker app.transactions.taskiq_broker:broker 
             --workers ${WORKERS:-2}
             --fs-discover
             --tasks-pattern 'tasks/*.py'
             --log-level info"

volumes:
  users_postgres_data:
  transaction_postgres_data:
  rabbitmq-data:
  redis-data:

networks:
  default:
    name: app-network
    driver: bridge