dynaconf_merge = true

[development]
log_level = "DEBUG"

[development.db]
url = "postgresql+asyncpg://postgres:postgres@db:5432/task_db"
pool_size = 20
max_overflow = 10
pool_timeout = 30

[development.server]
frontend_base_url = "http://localhost:3000"
help_center_url = "http://localhost:3000"
set_password_path = "/lifecycle/set-password"