from fastapi import HTTPException


class UserAlreadyExistsException(HTTPException): ...

class UserNotExistsException(HTTPException): ...

class UserAlreadyBlockedException(HTTPException): ...

class UserAlreadyActiveException(HTTPException): ...

class BadRequestDataException(HTTPException): ...

class NegativeBalanceException(HTTPException): ...

class TransactionNotExistsException(HTTPException): ...

class TransactionDoesNotBelongToUserException(HTTPException): ...

class CreateTransactionForBlockedUserException(HTTPException): ...

class UpdateTransactionForBlockedUserException(HTTPException): ...

class TransactionAlreadyRollbackedException(HTTPException): ...